services:
  cidadeinteligente.mvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=db,1433;Database=${DATABASE_NAME};User=${DATABASE_USER};Password=${DATABASE_PASSWORD};TrustServerCertificate=True
      - ConnectionStrings__FileStorage=${CONNECTIONSTRINGS__FILESTORAGE}
      - SendGrid__ApiKey=${SENDGRID_APIKEY}
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro