services:
  cidadeinteligente.mvc:
    image: ${DOCKER_REGISTRY-}cidadeinteligentemvc
    build:
      context: .
      dockerfile: CidadeInteligente.Mvc/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=CidadeInteligente;User=sa;Password=Adm1n23%;TrustServerCertificate=True
      - AzureStorage__ConnectionString=DefaultEndpointsProtocol=https;AccountName=testedfsggdsfdfgs5464563;AccountKey=OQ69eqgiwWQi3OmMsp+olLqQX1zfp+Ef0JUD+bAzmGA1Z29xSG7AJLO4n52QFsIfRnEooij3Df8o+AStsJqI4g==;EndpointSuffix=core.windows.net
      - SendGrid__ApiKey=

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      MSSQL_SA_PASSWORD: "Adm1n23%"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data: