services:
  cidadeinteligente.mvc:
    image: ${DOCKER_REGISTRY-}cidadeinteligentemvc
    build:
      context: .
      dockerfile: CidadeInteligente.Mvc/Dockerfile
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      MSSQL_SA_PASSWORD: ${DATABASE_PASSWORD}
      ACCEPT_EULA: "Y"

    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
