services:
  cidadeinteligente.ui:
    image: ${DOCKER_REGISTRY-}cidadeinteligenteui
    build:
      context: .
      dockerfile: CidadeInteligente.UI/Dockerfile

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      MSSQL_SA_PASSWORD: "Adm1n23%"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql # Apontando um volume para persistir os dados do SQL Server

volumes:
  sql_data: