apiVersion: apps/v1
kind: Deployment
metadata:
  name: cidade-inteligente-mvc-sqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cidade-inteligente-mvc-sqlserver
  template:
    metadata:
      labels:
        app: cidade-inteligente-mvc-sqlserver
    spec:
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cidade-inteligente-mvc-secret
              key: DATABASE_PASSWORD
        resources:
          limits:
            memory: "1.5Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: cidade-inteligente-mvc-sqlserver
spec:
  selector:
    app: cidade-inteligente-mvc-sqlserver
  ports:
  - port: 1433
    targetPort: 1433
