apiVersion: v1
kind: Secret
metadata:
  name: cidade-inteligente-mvc-secret
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Server=cidade-inteligente-mvc-sqlserver,1433;Database=CidadeInteligente;User Id=sa;Password=Users!Passw0rd;TrustServerCertificate=True"
  AzureStorage__ConnectionString: ""
  SendGrid__ApiKey: ""
